# Generated by Django 4.2.13 on 2024-06-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='/', upload_to='public/static/'),
        ),
    ]
